### ISSUE TITLE
Specialist Action sometimes not added

### ISSUE THREAD

**Issue by orkaboy** [drewg13/foundryvtt-band-of-blades#1] opened 2022-05-25 19:08 UTC
When creating a new character sheet and selecting a class (example: Heavy), sometimes the sheet refuses to add the specialist action (ie: Anchor) to the list. This doesn't always happen, but I've had to recreate sheets from scratch since it refused to work.

Additionally, a question: If the PCs choose to add XP to their Specialist tracker and manage to add a new specialist action (ie, a heavy with Aim or something), how can one add this new action to the list?

**Comment by drewg13** [comment] 2022-05-26 01:50
This one is tricky to figure out, unless you have reproducible steps to consistently trigger the issue.  One thing that would help would be if you could find an Actor currently having the issue and export the .json file for me to look at.

For your question, there's no built-in UI for that.  I don't recall anything in the rules that would allow you to add a new specialist action, although I might have missed that somewhere.  My understanding of the specialist XP tracker was that it increased the number of times you could use your legacy specialist action.  If that's something you need to do though, I can give you a macro to use.  Just select the token of the Actor you want to modify and run this in the console or as a script macro.  Substitute the name of the action you want to add for `weave`, in this example, but don't change anything else:
`await canvas.tokens.controlled[0].actor.update({'data.attributes.specialist.skills.weave':{value:'1', max:3}})`

**Comment by orkaboy** [comment] 2022-05-26 17:44
I may also be getting the rules wrong (first time DMing BoB, though I have a lot of experience with BitD before that), but my understanding is that any character regardless of class can learn any specialist action (Weave being the on-the-GM's-permission exception) by filling up the specialist XP track. Once you have your first rank, it would be added under the Insight grouping.

The one place I can find in the rulebook that specifically supports this is page 107 (Soldier: Specialist Training). The example given is:

> [When promoting,] You gain a rank of the Specialist's ability, so in this example, you would gain a rank of AIM. If you already have AIM, this would increase your rank by 1, up to the maxiumum rank allowed for your character, usually 3.

This would indicate that this is a valid thing to do (not to mention the other example given in the next pages where a soldier promotes to officer, transferring his current 3 GRIT and also gaining 1 CHANNELS, a functionality that the sheet should explicitly support if it doesn't already).

If I run into the bug again, I'll get back to you with the .json file, thanks for the macro.

**Comment by orkaboy** [comment] 2022-05-26 17:46
> My understanding of the specialist XP tracker was that it increased the number of times you could use your legacy specialist action.

I'm pretty sure this is not the case. If you are a Heavy for example, the way to increase Anchor is to put XP in Insight.

**Comment by orkaboy** [comment] 2022-05-26 18:07
I've been able to recreate the issue reliably. As improbable as it might seem, the issue appears to arise once the default avatar on the sheet (ie the portrait next to the name/class/heritage) is changed. When I create a new character, change the avatar to something custom, then change the class, the specialist action is not added. See below an officer without a rank in Channels:

https://pastebin.com/3EeBGuY7

I am using a module called **Tokenizer** that might be causing some kind of interference, but what exactly that would be I don't know. It just creates a non-standard image for portrait/token and puts in a link to that.

**Comment by drewg13** [comment] 2022-05-26 23:15
>I may also be getting the rules wrong (first time DMing BoB, though I have a lot of experience with BitD before that), but my understanding is that any character regardless of class can learn any specialist action (Weave being the on-the-GM's-permission exception) by filling up the specialist XP track. Once you have your first rank, it would be added under the Insight grouping.
>The one place I can find in the rulebook that specifically supports this is page 107 (Soldier: Specialist Training). The example given is:
>> [When promoting,] You gain a rank of the Specialist's ability, so in this example, you would gain a rank of AIM. If you already have AIM, this would increase your rank by 1, up to the maxiumum rank allowed for your character, usually 3.

I'll qualify this by saying that I have neither played nor GMed BoB.  I was taken by a fey mood and decided that it was a thing that I wanted to exist.  I love Black Company/Malazan, but my particular player group couldn't possibly be less interested in military or grimdark style play.  If the system is a little rough around the edges, it's because it has received next to zero actual play feedback, so yours is appreciated, even if I don't end up taking every suggestion.

That said, your interpretation is not even a little bit how I interpreted it and, frankly, I still don't see it that way at all.  My reading of it (and the way the system is designed) is that characters that start as Rookies do not have a Specialist Ability.  Once they promote to Soldier, they gain one rank of the Grit action (pg 99).  As a Soldier, filling the Insight XP bar may add additional ranks of the Grit action, which allows additional uses of the ability (pg 12).  When a Soldier promotes through Specialist Training, he moves the Grit action to the Specialist category, along with its current rank, and gains the specific Specialist action that goes with the chosen Specialist Playbook, replacing Grit under Insight with one rank.  This is analogous to the Rookie ability carrying forward as a benefit to promoting a character through the ranks, rather than creating a Specialist from the beginning.  Once this is done, the Specialist XP track allows that character to continue to increase the rank of the Grit action, while the Insight XP track allows them to increase the rank of their specific Specialist ability.  Also, see pg 57 that directly addresses what you can do when you fill an XP track.  The only option listed for taking an advance for an attribute is to increase an action rating.  I don't see anywhere in the book that talks about picking a new Specialist action and the above mechanism is the only way you could continue to increase the Grit action rank, once on a Specialist Playbook.  The Specialist Abilities are tightly tied to the theme of the Specialist, it doesn't make any sense at all to me that you would be able to choose additional abilities from other Specialties, effectively creating a "generalist" Specialist, without explicit language to that effect in the rules.  The only real support for this I see in the rules is in the Weave example on pg 304, but allowing Weave is pretty explicitly going off-piste already and even refers to designing a custom playbook, which my system also supports with a little effort.

All of that said, you run your game the way you like, that's why I supplied you with the macro you can use to arbitrarily add Specialist actions.  Another way to go about it is to promote a character from Soldier to (for example) Sniper by changing the class, then from Sniper to Medic by changing the class again.  This should leave you with a character with Specialist actions of Grit and Aim under Specialist and a Specialist action of Doctor under Insight.  The system was designed to explicitly support this type of advancement through the ranks with characters never losing Specialist actions from their previous classes.  This aspect was a real pain in the ass to design properly.

I'll take a look at the Actor you provided this weekend and I very much appreciate you finding repro steps for the bug.

**Comment by drewg13** [comment] 2022-05-27 01:43
>When I create a new character, change the avatar to something custom, then change the class, the specialist action is not added.

Wild as it is, I can confirm this without Tokenizer.  I don't have the vaguest idea what it could be, which is unusual, but when it's something bizarre like this, it's usually a namespace issue.  I'll keep digging at it.

**Comment by orkaboy** [comment] 2022-05-27 05:34
I'm guessing it has something to do with the class-change also trying to change the icon of the character sheet. Maybe it terminates early if it's not allowed to do that when the default is overridden. I don't see any error output in the console tho.

> That said, your interpretation is not even a little bit how I interpreted it and, frankly, I still don't see it that way at all.

I still maintain that the only way that the following direct quote from the book would make sense is if the specialist XP tracker worked the way I stated (how else would a Soldier get hold of AIM prior to becoming a Sniper?) [Rulebook, pg 107, Soldier/Specialist Training]:

> [When promoting,] You gain a rank of the Specialist's ability, so in this example, you would gain a rank of AIM. If you already have AIM, this would increase your rank by 1, up to the maxiumum rank allowed for your character, usually 3.

**Comment by orkaboy** [comment] 2022-05-27 06:08
> Once you have your first rank, it would be added under the Insight grouping.

On second thought, this particular thing is probably a bad take by me; it would probably stay under specialist unless you actually change to that class.

**Comment by orkaboy** [comment] 2022-05-27 07:05
> Just select the token of the Actor you want to modify and run this in the console or as a script macro. Substitute the name of the action you want to add for weave, in this example, but don't change anything else:
`await canvas.tokens.controlled[0].actor.update({'data.attributes.specialist.skills.weave':{value:'1', max:3}})`

Just as a note, I played around with this a little and got it to work correctly, with one minor caveat: it doesn't work for rookies because their specialist action category isn't shown. I think I can live with that limitation. I made a macro for it that can set any specialist skill through a dialog: https://pastebin.com/8dDVrU0g

**Comment by drewg13** [comment] 2022-05-27 13:27
>it doesn't work for rookies because their specialist action category isn't shown.

By the rules, "As Rookie, you start without a Specialist action.  When you gain your first advance, you will promote [to Soldier]..." (pg 99) and "Rookies must take this ability as their first advance..." (pg 101).  By my interpretation, there shouldn't be a scenario in which a Rookie should have a Specialist action, but I suppose it's possible that they put XP into attributes, rather than playbook advances and you *could* interpret "must" as only referring to playbook advances specifically, rather than all advances generally.   I can make the category contingent on whether or not a character has a Specialist action, rather than on whether they have a class which grants them a Specialist action.  A fine distinction that I hadn't thought to make before.

>I still maintain that the only way that the following direct quote from the book would make sense is if the specialist XP tracker worked the way I stated (how else would a Soldier get hold of AIM prior to becoming a Sniper?) [Rulebook, pg 107, Soldier/Specialist Training]:
>> [When promoting,] You gain a rank of the Specialist's ability, so in this example, you would gain a rank of AIM. If you already have AIM, this would increase your rank by 1, up to the maxiumum rank allowed for your character, usually 3.

Honestly, I thought, if this was true, it would have some explicit support in the rules text, but apparently this is the intended interpretation.

https://bitd.gplusarchive.online/2018/07/26/stras-acimovic-i-have-some-band-of-blades-questions/

>9. Can Soldiers and Specialists put xp into the ‘Specialist’ Attribute to gain ranks in other Specialist actions? Does a Soldier keep their Grit when they Promote to a Specialist?

Per Stras:
>9. Duan 100%. Yes and Yes.

I'll have to re-think providing UI to do this, rather than just the macro.  Shouldn't be that difficult though.  Probably just a little plus icon next to the Specialist XP tracker.

**Comment by drewg13** [comment] 2022-05-27 13:40
>I'm guessing it has something to do with the class-change also trying to change the icon of the character sheet. Maybe it terminates early if it's not allowed to do that when the default is overridden. I don't see any error output in the console tho.

That is a very insightful comment and strikes me as likely to be at least partially correct.

**Comment by orkaboy** [comment] 2022-05-27 14:57
> "Rookies must take this ability as their first advance..." (pg 101).

This sentence essentially means that a Rookie can only take two Special Abilities, the first which they get on character creation and the second being the promotion to Soldier. It's essentially to block you from taking more than one Rookie ability (which are quite good mechanically). However, the game has five different XP tracks (Playbook, Insight, Prowess, Resolve, Specialist), and this restriction only applies to the Playbook one. That is my reading of the rules at least.

**Comment by drewg13** [comment] 2022-05-27 15:17
Personally, I think doing anything with XP other than getting to that Soldier promotion is nuts, but I suppose you can do it.  Just pushed the fixes for this, going into the next version.

**Comment by drewg13** [comment] 2022-05-27 15:49
>I'm guessing it has something to do with the class-change also trying to change the icon of the character sheet. Maybe it terminates early if it's not allowed to do that when the default is overridden. I don't see any error output in the console tho.

Yup, it was an `if()` that I didn't close out properly that was intended to prevent overwriting custom art on class changes.  Easy fix, going into version 1.6.0.  Poor testing on my part.  Won't be the last I find, I'm sure.

**Closed by drewg13** 2022-05-27 15:49 UTC

**Comment by orkaboy** [comment] 2022-05-27 16:29
Awesome! I'll holler if I find more stuff.

**Comment by orkaboy** [comment] 2022-05-28 07:02
The bug appears to be fixed. Also nice that you added the add button on Specialist actions!

**Comment by drewg13** [comment] 2022-05-28 13:19
The buttons were an obvious and simple addition, once I was already looking at the sheets.  Not sure why I didn't add them before.

**Comment by drewg13** [comment] 2022-05-28 13:20
Oops, I thought you were referring to the QM Materiel and Personnel buttons, those were easy.  This was somewhat complex, but useful.
